import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";
import TechBackground from "@/app/components/TechBackground";
import Footer from "@/app/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LuMInA 2K25",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" type="image/png" sizes="128x128" href="/Logo.png" />
        <title>LuMInA 2K25</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TechBackground />
        <Nav />       
        {children}
        <Footer />
      </body>
    </html>
  );
}
